// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjnigzpgabzsnkgefnxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqbmlnenBnYWJ6c25rZ2VmbnhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MzYzMTMsImV4cCI6MjA2MzQxMjMxM30.E3QWA93FOtGxLa7VUIUDpuYIau_HlJnTN7a7NPJLpg4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);